### ISSUE TITLE
No Instruction -100

### ISSUE THREAD

**Issue by jules-pecaoco** [rafaeljacov/tictactoe_minimax#1]
how to run this

**Comment by rafaeljacov** [comment]
> how to run this

hey sorry i didn't document much because this was our project and it's done. To run this, you need to install love2d and have also lua because love2d uses it. if your'e using linux, you can download both love2d and lua using your package manager, for windows, you need to download the installer and the same for lua. May I ask what OS are you using?

**Comment by jules-pecaoco** [comment]
im using Windows11 :>

**Comment by rafaeljacov** [comment]
> im using Windows11 :>

you can now download the game from the [releases page](https://github.com/rafaeljacov/tictactoe_minimax/releases/tag/v1.0.0)
